from abc import ABC, abstractmethod
import math
from enum import IntEnum
from typing import Any, List, Optional, Literal, Tuple, Type
import numpy as np

class DataNode(ABC):
    """
    Base class for HLS Data Structure generation.

    All hardware-mappable types (Scalar, Array, Struct, Union) inherit 
    from this. 

    Parameters
    ----------
    name : str
        The name of this data node, used for C++ field naming and code generation.
    description : Optional[str]
        An optional human-readable description of this field, useful for documentation and code comments.
    """
    def __init__(
            self, 
            name: str, 
            description: Optional[str] = None):
        self.name = name
        self.description = description

    @abstractmethod
    def get_bitwidth(self) -> int:
        """Returns the total number of bits this node occupies in hardware."""
        pass

    @classmethod
    def cpp_class_name(cls) -> str:
        """Gets the C++ class name for this DataNode type, used in code generation.
        By default, this is the same as the Python class name (e.g., 'ComplexSample').
        For fields, this will be overridden to return the cpp_type (e.g., 'ap_int<16>').
        """
        return cls.__name__

    @abstractmethod
    def gen_pack(self, 
                 indent_level: int = 0) -> str:
        """
        Generates the Vitis C++ code for a 'pack_to_uint' method.

        constexpr int C::bitwidth = ...;
        static ap_uint<C::bitwidth> C::pack_to_uint(const C& data) {
        }

        This function maps the internal fields to a single wide ap_uint<W>.
        """
        raise NotImplementedError("gen_pack must be implemented by subclasses of DataNode.")

    @abstractmethod
    def gen_unpack(self,
                   indent_level: int = 0) -> str:
        """
        Generates the Vitis C++ code for an 'unpack_from_uint' method.

        C C::unpack_from_uint(const ap_uint<C::bitwidth>& packed) {
        }

        This function maps a packed ap_uint<W> back into the internal fields.
        """
        raise NotImplementedError("gen_unpack must be implemented by subclasses of DataNode.")

    @abstractmethod
    def default_value(self) -> Any:
        """
        Returns the default Python-side value for this node.
        """
        raise NotImplementedError("default_value must be implemented by subclasses of DataNode.")
    
    def nwords_per_inst(self, word_bw: int) -> int:
        """
        Utility to compute how many words of a given bandwidth 
        are needed to represent this node.  The computation assuems the same
        packing as in gen_write()
        """
        if word_bw <= 0:
            raise ValueError("word_bw must be positive.")

        final_ipos, final_iword = self._nwords_per_inst_recursive(
            word_bw=word_bw,
            ipos0=0,
            iword0=0,
        )
        return final_iword + (1 if final_ipos > 0 else 0)
    
    def gen_write(
        self, 
        word_bw: int, 
        dst_type: Literal["array", "stream", "axi4_stream"] = "array"
    ) -> str:
        """
        Generates the C++ boiler plate for writing the data structure 
        to a specific hardware interface.  The code generated will depend on the dst_type and
        will look like one of the following templates:

        if dst_type == "array":
            template<>
            void C::write_array(ap_uint<word_bw> x[]) { 
                // body generated by _gen_write_recursive, which will contain lines like:
                x[0] = ...;
                x[1] = ...;
            }

        elif dst_type == "stream":
            template<>
            void C::write_stream(hls::stream<ap_uint<word_bw>> &s) {
                // body generated by _gen_write_recursive, which will contain lines like:
                ap_uint<word_bw> w =...;
                s.write(w);
                ap_uint<word_bw> w =...;
                s.write(w);
            }

        elif dst_type == "axi4_stream":
            template<>
            void C::write_axi4_stream(
                hls::stream<hls::axis<ap_uint<word_bw>, 0, 0, 0>> &s, bool tlast = true) { 
                 // body generated by _gen_write_recursive, which will contain lines like:
                ap_uint<word_bw> w =...;
                streamutils::write_axi4_word<word_bw>(s, w, tlast);
            }
        
        where `C` is the C++ class name corresponding to this DataNode and `...`
        is the body generated by the recursive engine `_gen_write_recursive`.

        Parameters
        ----------
        word_bw : int
            The bitwidth of the hardware interface word. This determines how the data 
            fields are packed into words.
        dst_type : Literal["array", "stream", "axi4_stream"]
            The type of hardware interface to generate code for. 
            This affects the function signature and how data is written.
        """
        class_name = self.cpp_class_name()
        
        # 1. Generate the Header based on interface type
        if dst_type == "array":
            header = [f"template<>", f"void {class_name}::write_array<{word_bw}>(ap_uint<{word_bw}> x[]) {{"]
            target = "x"
        elif dst_type == "stream":
            header = [f"template<>", f"void {class_name}::write_stream<{word_bw}>(hls::stream<ap_uint<{word_bw}>> &s) {{"]
            target = "s"
        else: # axi4_stream
            header = [f"template<>", f"void {class_name}::write_axi4_stream<{word_bw}>(hls::stream<hls::axis<ap_uint<{word_bw}>, 0, 0, 0>> &s, bool tlast = true) {{"]
            target = "s"

        body_lines = []
        # Initialize the word buffer if we are streaming
        if dst_type != "array":
            body_lines.append(f"    ap_uint<{word_bw}> w = 0;")
        
        # 2. Call the recursive engine
        # ipos: bit position in current word, iword: current word index
        final_lines, final_ipos, final_iword = self._gen_write_recursive(
            word_bw=word_bw, 
            dst_type=dst_type, 
            target=target, 
            ipos0=0, 
            iword0=0,
            prefix="this->"
        )
        body_lines.extend(final_lines)

        # 3. Final Flush for streams if bits are left in the buffer
        if dst_type != "array" and final_ipos > 0:
            if dst_type == "stream":
                body_lines.append(f"    {target}.write(w);")
            else:
                body_lines.append(f"    streamutils::write_axi4_word<{word_bw}>({target}, w, tlast);")

        return "\n".join(header + body_lines + ["}"])

    def gen_write_mult(
        self, 
        word_bw: int, 
        dst_type: Literal["array", "stream", "axi4_stream"] = "array"
    ) -> str:
        """
        Generates the C++ function for writing multiple instances of a data structure 
        to a specific hardware interface.  The code generated will depend on the dst_type and
        will look like one of the following templates:

        if dst_type == "array":
            template<>
            void write_array_mult<C,word_bw>(const C src[], ap_uint<word_bw> dst[], int n) { ...  }

        elif dst_type == "stream":
            template<>
            void write_stream_mult<C,word_bw>(const C src[],hls::stream<ap_uint<word_bw>> &s, int n) {... };

        elif dst_type == "axi4_stream":
            template<>
            void write_axi4_stream_mult<C,word_bw>(
                hls::stream<hls::axis<ap_uint<word_bw>, 0, 0, 0>> &s, int n, bool tlast = true) { 
            }
        
        where `C` is the C++ class name corresponding to this DataNode and `...`
        is the body and `n` is the number of instances to write.  There are two cases,
        depending on the packing factor:

            pf = floor(word_bw / C.bitwidth)

        Case 1:  If pf >= 2, we can pack two or more instances into a each word.

        In this case, for example, for dst_type="array" case, the code will look like:
            for (int i = 0; i < n/pf; i++) {
                # pragma to pipeline this loop
                for (int j = 0; j < pf; j++) {
                    # pragma to unroll this inner loop
                    ap_uint<word_bw> w = 0;
                    w.range(...) = {to_uint_expr}(data[i*pf + j]);
                dst[i] = w;
            // Code to hand the final partial word if n is not divisible by pf
                

        Case 2: If pf < 2, we pack only one instance per word, and the code will look like:
            for (int i = 0; i < n; i++) {
                C::write_array(src[i], &dst[i*words_per_inst]);

        Parameters
        ----------
        word_bw : int
            The bitwidth of the hardware interface word. This determines how the data 
            fields are packed into words.
        dst_type : Literal["array", "stream", "axi4_stream"]
            The type of hardware interface to generate code for. 
            This affects the function signature and how data is written.
        """
        class_name = self.cpp_class_name()
        inst_bw = self.get_bitwidth()
        pf = word_bw // inst_bw if inst_bw > 0 else 0
        words_per_inst = self.nwords_per_inst(word_bw)

        if dst_type == "array":
            header = [
                "template<>",
                f"void write_array_mult<{class_name}, {word_bw}>(const {class_name} src[], ap_uint<{word_bw}> dst[], int n) {{",
            ]
        elif dst_type == "stream":
            header = [
                "template<>",
                f"void write_stream_mult<{class_name}, {word_bw}>(const {class_name} src[], hls::stream<ap_uint<{word_bw}>> &s, int n) {{",
            ]
        else:
            header = [
                "template<>",
                f"void write_axi4_stream_mult<{class_name}, {word_bw}>(const {class_name} src[], hls::stream<hls::axis<ap_uint<{word_bw}>, 0, 0, 0>> &s, int n, bool tlast = true) {{",
            ]

        body_lines = [
            f"    constexpr int inst_bw = {inst_bw};",
            f"    constexpr int pf = {pf};",
            f"    constexpr int words_per_inst = {words_per_inst};",
        ]

        if pf >= 2:
            body_lines.extend([
                "    int out_idx = 0;",
                "    int i = 0;",
            ])

            if dst_type == "axi4_stream":
                body_lines.append("    const int total_words = (n + pf - 1) / pf;")

            body_lines.extend([
                "    for (; i + pf <= n; i += pf) {",
                "        #pragma HLS PIPELINE II=1",
                f"        ap_uint<{word_bw}> w = 0;",
            ])

            for j in range(pf):
                low = j * inst_bw
                high = low + inst_bw - 1
                body_lines.append(
                    f"        w.range({high}, {low}) = {class_name}::pack_to_uint(src[i + {j}]);"
                )

            if dst_type == "array":
                body_lines.append("        dst[out_idx++] = w;")
            elif dst_type == "stream":
                body_lines.append("        s.write(w);")
                body_lines.append("        out_idx++;")
            else:
                body_lines.append("        const bool last = (out_idx == total_words - 1) ? tlast : false;")
                body_lines.append(f"        streamutils::write_axi4_word<{word_bw}>(s, w, last);")
                body_lines.append("        out_idx++;")

            body_lines.append("    }")

            body_lines.extend([
                "    if (i < n) {",
                "        #pragma HLS PIPELINE II=1",
                f"        ap_uint<{word_bw}> w = 0;",
            ])

            for j in range(pf):
                low = j * inst_bw
                high = low + inst_bw - 1
                body_lines.extend([
                    f"        if (i + {j} < n) {{",
                    f"            w.range({high}, {low}) = {class_name}::pack_to_uint(src[i + {j}]);",
                    "        }",
                ])

            if dst_type == "array":
                body_lines.append("        dst[out_idx++] = w;")
            elif dst_type == "stream":
                body_lines.append("        s.write(w);")
            else:
                body_lines.append("        const bool last = (out_idx == total_words - 1) ? tlast : false;")
                body_lines.append(f"        streamutils::write_axi4_word<{word_bw}>(s, w, last);")

            body_lines.append("    }")

        else:
            body_lines.extend([
                "    for (int i = 0; i < n; ++i) {"
            ])

            # Add the pipelining pragma if there is only one word per instance
            if words_per_inst == 1:
                body_lines.append("        #pragma HLS PIPELINE II=1")

            if dst_type == "array":
                if words_per_inst == 1:
                    body_lines.append(f"        dst[i] = {class_name}::pack_to_uint(src[i]);")
                else:
                    body_lines.append(f"        src[i].write_array<{word_bw}>(&dst[i * words_per_inst]);")
            elif dst_type == "stream":
                body_lines.append(f"        src[i].write_stream<{word_bw}>(s);")
            else:
                body_lines.append("        const bool last = (i == n - 1) ? tlast : false;")
                body_lines.append(f"        src[i].write_axi4_stream<{word_bw}>(s, last);")

            body_lines.append("    }")

        return "\n".join(header + body_lines + ["}"])

    @abstractmethod
    def _gen_write_recursive(
        self, 
        word_bw: int, 
        dst_type: Literal["array", "stream", "axi4_stream"] = "array",
        target: Literal["x", "s"] = "x", 
        ipos0: int = 0, 
        iword0: int = 0, 
        prefix: str = ""
    ) -> Tuple[List[str], int, int]:
        """
        Recursive helper. 
        Returns (list of C++ lines, final_bit_pos, final_word_index).
        """
        raise NotImplementedError("Subclasses must implement _gen_write_recursive")

    @abstractmethod
    def _nwords_per_inst_recursive(
        self,
        word_bw: int,
        ipos0: int = 0,
        iword0: int = 0,
    ) -> Tuple[int, int]:
        """
        Recursive helper used by nwords_per_inst.
        Returns (final_bit_pos, final_word_index).
        """
        raise NotImplementedError("Subclasses must implement _nwords_per_inst_recursive")

    def _get_indent(self, level: int) -> str:
        """Utility for consistent C++ code formatting."""
        return "    " * level
    

    def to_uint_expr(
            self,
            prefix : Optional[str] = None) -> str:
        """
        Returns a C++ expression that converts a DataNode instance
        to an unsigned integer representation.  By default,
        this calls the static pack_to_uint method of the corresponding 
        C++ class.

        For DataField nodes, this will be overridden to return 
        the field value directly (with any necessary conversions).
        """
        if prefix is None:
            prefix = ""
        return f"{self.cpp_class_name()}::pack_to_uint({prefix}{self.name})"

    def from_uint_expr(self, uint_expr: str) -> str:
        """
        Returns a C++ expression that converts an unsigned integer slice back
        to this node's C++ representation.
        """
        return f"{self.cpp_class_name()}::unpack_from_uint({uint_expr})"
    
    def gen_cpp_class(self) -> str:
        """
        Generates the C++ class definition. 

        For example, for DataField, this is just a typedef using cpp_type.
        For DataList, this is a class with fields corresponding to the elements.
        """
        raise NotImplementedError("gen_cpp_class must be implemented by subclasses of DataNode.")
    

class DataField(DataNode):
    """
    Represents a basic data field with a specific C++ type and bitwidth.
    These nodes are the leaves of the data schema tree and 
    correspond to actual data fields in the generated C++ struct.
    """
    def __init__(
            self, 
            name: str, 
            cpp_type: str,
            bitwidth: int, 
            description: Optional[str] = None):
        super().__init__(name, description)
        self.bitwidth = bitwidth
        self.cpp_type = cpp_type

    def get_bitwidth(self) -> int:
        return self.bitwidth
    
    def cpp_class_name(self) -> str:
        """For DataField, the C++ class name is just the cpp_type."""
        return self.cpp_type
    
    def gen_pack(self, indent_level: int = 0) -> str:
        # DataFields don't generate their own pack function; 
        # they are packed by their parent StructNode.
        return ""

    def gen_unpack(self, indent_level: int = 0) -> str:
        # DataFields don't generate their own unpack function;
        # they are unpacked by their parent StructNode.
        return ""
    
    def _gen_write_recursive(
        self, 
        word_bw: int, 
        dst_type: Literal["array", "stream", "axi4_stream"] = "array",
        target: Literal["x", "s"] = "x", 
        ipos0: int = 0, 
        iword0: int = 0, 
        prefix: str = ""
    ) -> Tuple[List[str], int, int]:
        """
        Implement the logic to write this field into the target interface.
        If word_bw < self.bitwidth, raise an error since we don't split individual 
        fields across words.  
        """
        if self.bitwidth > word_bw:
            raise ValueError(
                f"Field '{self.name}' with bitwidth {self.bitwidth} cannot fit into word_bw={word_bw}."
            )

        lines: List[str] = []
        curr_ipos = ipos0
        curr_iword = iword0

        if curr_ipos + self.bitwidth > word_bw:
            if dst_type == "stream":
                lines.append(f"    {target}.write(w);")
                lines.append("    w = 0;")
            elif dst_type == "axi4_stream":
                lines.append(f"     streamutils::write_axi4_word<{word_bw}>({target}, w, false);")
                lines.append("    w = 0;")

            curr_iword += 1
            curr_ipos = 0

        lhs = "w" if dst_type != "array" else f"{target}[{curr_iword}]"
        val_expr = self.to_uint_expr(prefix)

        if curr_ipos == 0 and self.bitwidth == word_bw:
            lines.append(f"    {lhs} = {val_expr};")
        else:
            if dst_type == "array" and curr_ipos == 0:
                lines.append(f"    {target}[{curr_iword}] = 0;")

            high = curr_ipos + self.bitwidth - 1
            low = curr_ipos
            lines.append(f"    {lhs}.range({high}, {low}) = {val_expr};")

        curr_ipos += self.bitwidth

        if curr_ipos == word_bw:
            if dst_type == "stream":
                lines.append(f"    {target}.write(w);")
                lines.append("    w = 0;")
            elif dst_type == "axi4_stream":
                lines.append(f"    streamutils::write_axi4_word<{word_bw}>({target}, w, false);")
                lines.append("    w = 0;")

            curr_iword += 1
            curr_ipos = 0

        return lines, curr_ipos, curr_iword

    def _nwords_per_inst_recursive(
        self,
        word_bw: int,
        ipos0: int = 0,
        iword0: int = 0,
    ) -> Tuple[int, int]:
        """
        Computes final (bit_pos, word_index) state after packing this field,
        matching the same boundary behavior used by _gen_write_recursive.
        """
        if self.bitwidth > word_bw:
            raise ValueError(
                f"Field '{self.name}' with bitwidth {self.bitwidth} cannot fit into word_bw={word_bw}."
            )

        curr_ipos = ipos0
        curr_iword = iword0

        if curr_ipos + self.bitwidth > word_bw:
            curr_iword += 1
            curr_ipos = 0

        curr_ipos += self.bitwidth

        if curr_ipos == word_bw:
            curr_iword += 1
            curr_ipos = 0

        return curr_ipos, curr_iword


    def default_value(self) -> Any:
        return 0

    def gen_cpp_class(self) -> str:
        """
        Generates the C++ class definition via a typedef. For example, if cpp_type is "ap_int<16>", 
        this will generate:
            typedef ap_int<16> name;
        """
        return f"typedef    {self.cpp_type} {self.name};"

    def from_uint_expr(self, uint_expr: str) -> str:
        return f"({self.cpp_type})({uint_expr})"
   
class IntField(DataField):
    """
    Represents an integer field with a specified bitwidth and signedness.

    Parameters
    ----------
    name : str
    bitwidth : int, optional
        The bitwidth of the integer field (default is 32).
    signed : bool, optional
        Whether the integer is signed (default is True).
    """
    def __init__(
            self, 
            name: str, 
            bitwidth: int = 32, 
            signed: bool = True,
            **kwargs):
        
        if signed:
            cpp_type = f"ap_int<{bitwidth}>"
        else:
            cpp_type = f"ap_uint<{bitwidth}>"
        super().__init__(name, cpp_type, bitwidth,**kwargs)
        self.signed = signed

    def to_uint_expr(self, prefix: Optional[str] = None) -> str:
        # HLS handles ap_int/int to ap_uint conversion natively via assignment
        if prefix is None:
            prefix = ""
        return f"{prefix}{self.name}"

    def default_value(self) -> Any:
        if self.bitwidth > 64:
            num_words = math.ceil(self.bitwidth / 64)
            return np.zeros(num_words, dtype=np.uint64)

        if self.signed:
            return np.int32(0) if self.bitwidth <= 32 else np.int64(0)

        return np.uint32(0) if self.bitwidth <= 32 else np.uint64(0)

class FloatField(DataField):
    def __init__(
            self, 
            name: str,
            bitwidth : int = 32,
            **kwargs):
        
        if bitwidth not in (32, 64):
            raise ValueError("FloatField only supports 32 or 64 bit widths.")
        cpp_type = "double" if bitwidth == 64 else "float"
        super().__init__(name=name, bitwidth=bitwidth, cpp_type=cpp_type,
                          **kwargs)

    def to_uint_expr(self, prefix: Optional[str] = None) -> str:
        """Floats require bit_cast to avoid value conversion."""
        if prefix is None:
            prefix = ""
        return f"streamutils::float_to_uint({prefix}{self.name})"

    def default_value(self) -> Any:
        return np.float64(0.0) if self.bitwidth == 64 else np.float32(0.0)

    def from_uint_expr(self, uint_expr: str) -> str:
        if self.bitwidth != 32:
            raise ValueError("FloatField unpack currently supports only bitwidth=32.")
        return f"streamutils::uint_to_float((uint32_t)({uint_expr}))"


class EnumField(DataField):
    def __init__(
            self,
            name: str,
            enum_type: Type[IntEnum],
            bitwidth: Optional[int] = None,
            default: Optional[IntEnum] = None,
            **kwargs):

        if not issubclass(enum_type, IntEnum):
            raise TypeError("EnumField requires enum_type to derive from IntEnum.")

        enum_values = [int(member.value) for member in enum_type]
        if any(value < 0 for value in enum_values):
            raise ValueError("EnumField currently supports only non-negative IntEnum values.")

        min_width = (max(enum_values).bit_length() or 1) if enum_values else 1
        if bitwidth is None:
            bitwidth = min_width
        elif bitwidth < min_width:
            raise ValueError(
                f"bitwidth={bitwidth} is too small for enum {enum_type.__name__}; needs at least {min_width} bits."
            )

        super().__init__(name=name, cpp_type=enum_type.__name__, bitwidth=bitwidth, **kwargs)
        self.enum_type = enum_type

        if default is None:
            default = list(enum_type)[0]
        self._default_member = self._coerce(default)

    def _coerce(self, value: Any) -> IntEnum:
        try:
            return self.enum_type(value)
        except ValueError as exc:
            raise ValueError(f"Value '{value}' is not a valid member of {self.enum_type.__name__}") from exc

    def to_uint_expr(self, prefix: Optional[str] = None) -> str:
        if prefix is None:
            prefix = ""
        return f"(ap_uint<{self.bitwidth}>)({prefix}{self.name})"

    def default_value(self) -> Any:
        return self._default_member

    def from_uint_expr(self, uint_expr: str) -> str:
        return f"({self.enum_type.__name__})({uint_expr})"

    def gen_cpp_class(self) -> str:
        """
        Generates a C++ enum definition for this EnumField's enum_type, 
        along with a typedef for the field itself. For example:

            enum OpCode {
                READ = 0,
                WRITE = 1,
                SYNC = 2,
            };
        """
        enum_lines = [f"enum {self.enum_type.__name__} {{"]
        for member in self.enum_type:
            enum_lines.append(f"    {member.name} = {member.value},")
        enum_lines.append("};")
        return "\n".join(enum_lines)



class DataList(DataNode):
    """
    Represents a collection of DataNodes that correspond to fields in a C++ class.  This is
    the main way to define structured data types that will be mapped to C++ classes 
    with multiple fields.
    """
    def __init__(
        self, 
        name: str, 
        elements: List[DataNode] = None, 
        description: Optional[str] = None
    ):
        """
        Constructor

        Parameters
        ---------
        name : str
            The name of this data list, used for C++ class naming and code generation.
        elements : List[DataNode], optional
            A list of DataNode instances that are the fields/elements of this data list.
            You can also add elements later using the add_elem() method.
        description : Optional[str]
            An optional human-readable description of this data list, 
            useful for documentation and code comments.
        """
        super().__init__(name, description)
        self.elements = []
        if elements is None:
            elements = []
        for elem in elements:
            self.add_elem(elem)

    def add_elem(self, element: DataNode):
        """
        Adds a DataNode element to this DataList.

        This will also set the element as an attribute of this DataList instance, allowing
        you to access it as self.element_name.  The element's name must be unique among the 
        existing attributes.
        """
        self.elements.append(element)

        if not element.name:
            raise ValueError("DataList elements must have a non-empty name to be addressable as attributes.")

        if hasattr(self, element.name):
            raise ValueError(
                f"Cannot add element '{element.name}': attribute already exists on {self.__class__.__name__}."
            )

        setattr(self, element.name, element.default_value())

    def default_value(self) -> Any:
        return self.__class__(name=self.name)

    def get_bitwidth(self) -> int:
        """Sum of bitwidths of all children."""
        return sum(node.get_bitwidth() for node in self.elements)

    def gen_pack(self, indent_level: int = 0) -> str:
        """
        Generates the static pack_to_uint method for this collection.
        It iterates through elements and slices them into the wide ap_uint.
        """
        cls_name = self.cpp_class_name()
        total_bits = self.get_bitwidth()
        indent = self._get_indent(indent_level)
        inner_indent = self._get_indent(indent_level + 1)

        lines = [
            f"{indent}static constexpr int {cls_name}::bitwidth = {total_bits};",
            f"{indent}static ap_uint<{total_bits}> {cls_name}::pack_to_uint(const {cls_name}& data) {{",
            f"{inner_indent}ap_uint<{total_bits}> res = 0;"
        ]

        current_lsb = 0
        for node in self.elements:
            width = node.get_bitwidth()
            # We use the node's to_uint_expr, but we must prefix it with 'data.'
            # because the static method takes 'const C& data' as an argument.
            expr = node.to_uint_expr(prefix="data.") 
            high = current_lsb + width - 1
            low = current_lsb
            lines.append(f"{inner_indent}res.range({high}, {low}) = {expr};")
            current_lsb += width

        lines.append(f"{inner_indent}return res;")
        lines.append(f"{indent}}}")
        
        return "\n".join(lines)

    def gen_unpack(self, indent_level: int = 0) -> str:
        """
        Generates the static unpack_from_uint method for this collection.
        It slices the packed ap_uint and reconstructs each element.
        """
        cls_name = self.cpp_class_name()
        total_bits = self.get_bitwidth()
        indent = self._get_indent(indent_level)
        inner_indent = self._get_indent(indent_level + 1)

        lines = [
            f"{indent}{cls_name} {cls_name}::unpack_from_uint(const ap_uint<{total_bits}>& packed) {{",
            f"{inner_indent}{cls_name} data;"
        ]

        current_lsb = 0
        for node in self.elements:
            width = node.get_bitwidth()
            high = current_lsb + width - 1
            low = current_lsb
            slice_expr = f"packed.range({high}, {low})"
            rhs_expr = node.from_uint_expr(slice_expr)
            lines.append(f"{inner_indent}data.{node.name} = {rhs_expr};")
            current_lsb += width

        lines.append(f"{inner_indent}return data;")
        lines.append(f"{indent}}}")

        return "\n".join(lines)

    def gen_cpp_class(self) -> str:
        """
        Generates the C++ class definition for this DataList and its children.

        class ClassName {
        public:
            // Child elements as fields
            ChildType1 child1;
            ChildType2 child2;
            ...    
        }

        """
        class_name = self.cpp_class_name()
        lines: List[str] = [
            f"class {class_name} {{",
            "public:",
        ]

        for element in self.elements:
            elem_class = element.cpp_class_name()
            lines.append(f"    {elem_class} {element.name};")

        lines.extend([
            "",
            f"    static constexpr int bitwidth = {self.get_bitwidth()};",
            f"    static ap_uint<bitwidth> pack_to_uint(const {class_name}& data);",
            f"    static {class_name} unpack_from_uint(const ap_uint<bitwidth>& packed);",
            "",
            "};",
        ])

        return "\n".join(lines)

    def _gen_write_recursive(
        self, 
        word_bw: int, 
        dst_type: Literal["array", "stream", "axi4_stream"] = "array",
        target: Literal["x", "s"] = "x", 
        ipos0: int = 0, 
        iword0: int = 0, 
        prefix: str = ""
    ) -> Tuple[List[str], int, int]:
        """
        TODO:  Implement the logic to write lines for all the child elements,
        recurisvely calling their _gen_write_recursive methods and correctly updating
        and passing the bit position and word index as needed.
        """
        lines: List[str] = []
        curr_ipos = ipos0
        curr_iword = iword0

        child_prefix = prefix
        if prefix != "this->" and self.name:
            child_prefix = f"{prefix}{self.name}."

        for element in self.elements:
            elem_lines, curr_ipos, curr_iword = element._gen_write_recursive(
                word_bw=word_bw,
                dst_type=dst_type,
                target=target,
                ipos0=curr_ipos,
                iword0=curr_iword,
                prefix=child_prefix,
            )
            lines.extend(elem_lines)

        return lines, curr_ipos, curr_iword

    def _nwords_per_inst_recursive(
        self,
        word_bw: int,
        ipos0: int = 0,
        iword0: int = 0,
    ) -> Tuple[int, int]:
        curr_ipos = ipos0
        curr_iword = iword0

        for element in self.elements:
            curr_ipos, curr_iword = element._nwords_per_inst_recursive(
                word_bw=word_bw,
                ipos0=curr_ipos,
                iword0=curr_iword,
            )

        return curr_ipos, curr_iword