#include <fstream>
#include <cstdint>
#include <string>
#include <stdexcept>

#include "poly.hpp"
#include "include/float32_array_utils_tb.h"
#include "include/streamutils_tb.h"

int main(int argc, char** argv) {
    const std::string data_dir = (argc > 1) ? argv[1] : "data";

    // Read the input test data for the command header from files generated by the Python testbench
    PolyCmdHdr cmd_hdr;
    streamutils::read_uint32_file(cmd_hdr, (data_dir + "/cmd_hdr_data.bin").c_str());

    // Read the input test data for the samples from files generated by the Python testbench
    const int nsamp = cmd_hdr.nsamp;
    float samp_in[MAX_NSAMP] = {};
    float samp_out[MAX_NSAMP] = {};
    float32_array_utils::read_uint32_file_array(samp_in, (data_dir + "/samp_in_data.bin").c_str(), nsamp);

    // Create AXI4-Stream interfaces
    hls::stream<axis_word_t> in_stream;
    hls::stream<axis_word_t> out_stream;

    // Push the command header as its own TLAST-terminated burst.
    cmd_hdr.write_axi4_stream<WORD_BW>(in_stream, true);

    // Push the sample payload as a second TLAST-terminated burst.  To support wide bitwidths,
    // we push the samples in chunks of pf samples at a time, where pf is the number of float32
    // values that fit in WORD_BW bits.
    static const int pf = float32_array_utils::pf<WORD_BW>();
    for (int i = 0; i < nsamp; i += pf) {
        const int nrem = nsamp - i;
        const bool tlast = (nrem <= pf);
        float32_array_utils::write_axi4_stream_elem<WORD_BW>(in_stream, samp_in + i, tlast, nrem);
    }

    // Run the accelerator
    poly(in_stream, out_stream);

    // Read the three output bursts from the accelerator: response header, sample payload,
    // and response footer.  The sample payload is still read in chunks of pf words.
    PolyRespHdr resp_hdr;
    streamutils::tlast_status resp_hdr_tlast = streamutils::tlast_status::no_tlast;
    resp_hdr.read_axi4_stream<WORD_BW>(out_stream, resp_hdr_tlast);

    streamutils::tlast_status samp_out_tlast = streamutils::tlast_status::no_tlast;
    float32_array_utils::read_axi4_stream<WORD_BW>(out_stream, samp_out, samp_out_tlast, nsamp);

    PolyRespFtr resp_ftr;
    streamutils::tlast_status resp_ftr_tlast = streamutils::tlast_status::no_tlast;
    resp_ftr.read_axi4_stream<WORD_BW>(out_stream, resp_ftr_tlast);

    streamutils::write_uint32_file(resp_hdr, (data_dir + "/resp_hdr_data.bin").c_str());
    float32_array_utils::write_uint32_file_array(samp_out, (data_dir + "/samp_out_data.bin").c_str(), nsamp);
    streamutils::write_uint32_file(resp_ftr, (data_dir + "/resp_ftr_data.bin").c_str());

    std::ofstream sync_ofs(data_dir + "/sync_status.json");
    if (!sync_ofs) {
        throw std::runtime_error("Failed to open sync_status.json for writing.");
    }
    sync_ofs
        << "{\n"
        << "  \"resp_hdr_tlast\": \"" << streamutils::to_string(resp_hdr_tlast) << "\",\n"
        << "  \"samp_out_tlast\": \"" << streamutils::to_string(samp_out_tlast) << "\",\n"
        << "  \"resp_ftr_tlast\": \"" << streamutils::to_string(resp_ftr_tlast) << "\"\n"
        << "}\n";

    return 0;
}
